//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public int DetailId { get; set; }
        public int Quantity { get; set; }
        public int ShopId { get; set; }
        public System.DateTime PurchaseDateTime { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Shops Shops { get; set; }
    }
}
